### ISSUE TITLE
What would the hardware requirements be for the the 5B parameters model?

### ISSUE THREAD

**Issue by Njasa2k** [ali-vilab/composer#1]
What would the hardware requirements be for the the 5B parameters model? would it be possible on consumer grade hardware?

**Comment by huanglianghua** [comment]
With simple acceleration (i.e., half precision, flash attention), Composer requires approximately 28GB of GPU memory for inference.

It would be possible to further reduce the memory consumption with, e.g., uint8 quantization and TensorRT to make it run on consumer grade GPUs.

**Comment by huanglianghua** [comment]
@ninjasaid2k With simple acceleration (i.e., half precision, flash attention), Composer requires approximately 28GB of GPU memory for inference.

It would be possible to further reduce the memory consumption with, e.g., uint8 quantization and TensorRT to make it run on consumer grade GPUs.
